application: hostel-ku
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /student_details
  script: landing.py
  
- url: /rpc
  script: service.py
  
- url: /csv
  script: main_csv.py
  
- url: /upload_csv
  script: upload.py
  
- url: /upload
  script: upload.py
  
- url: /cron/update_data
  script: update_cron.py 

- url: /cron/open_application
  script: update_cron.py 

- url: /.*
  script: landing.py
